
def visualize(name):
    match name:
        case 'P':
            return '♟'
        case 'p':
            return '♙'
        case 'R':
            return '♜'
        case 'r':
            return '♖'
        case 'B':
            return '♝'
        case 'b':
            return '♗'
        case 'Q':
            return '♛'
        case 'q':
            return '♕'
        case 'K':
            return '♚'
        case 'k':
            return '♔'
        case 'N':
            return '♞'
        case 'n':
            return '♘'
        case _:
            return ''
